### ISSUE TITLE
C# Track courses to be completed

### ISSUE THREAD

**Issue by alexpmarks7** [alexpmarks7/Treehouse#2]
## TODO

*Courses left to complete the Treehouse C# Track*

* [ ] Introduction to Visual Studio
* [ ] Using GitHub with Visual Studio
* [ ] C# Basics
* [ ] C# Objetcs
* [ ] Intermediate C#
* [ ] C# Collections
* [ ] Unit Testing in C#

🎉  🎉  🎉
